apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-two
spec:
  project: cluster-templates
  sources:
  - repoURL: somewhere
    path: aws
    targetRevision: v1.1.11
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: default
    server: kubernetes
  syncPolicy:
    automated:
     prune: true
    syncOptions:
    - RespectIgnoreDifferences=true